language: node_js
node_js:
    - "node"
before_install:
    - npm install -g standard
    - npm install --save-dev mocha
    - npm i -D mocha puppeteer
    - npm install --save-dev chai
    - npm install showroom
    - npm install testcafe

script:
  - npm run lint
  - npm run test

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox