env:
    global:
        - CC_TEST_REPORTER_ID=133c121dd43557bc358549a7e9530ac24ddfb446620202a8a9239ab1f2cdfd43


language: node_js
node_js: "stable"

before_install:
    - stty cols 80
    - npm install -g standard
    - npm install --save-dev mocha
    - npm i -D mocha puppeteer
    - npm install --save-dev chai
    - npm install --showroom

before_script:
    - npm install codeclimate-test-reporter istanbul -g
    - npm install nyc
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

script:
    - npm run lint
    - npm run test "tests/unit/*.js"
    - npm run coveragetest
    - npm run browsertest

after_script:
  - ./cc-test-reporter after-build -t lcov -p /tests/unit --exit-code $TRAVIS_TEST_RESULT
